
package test1;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PaymentBrokerEndpoint", targetNamespace = "http://upbs.cs.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PaymentBrokerEndpoint {


    /**
     * 
     * @return
     *     returns java.util.List<test1.Region>
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "region", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getRegions", targetNamespace = "http://upbs.cs.com/", className = "test1.GetRegions")
    @ResponseWrapper(localName = "getRegionsResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetRegionsResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getRegionsRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getRegionsResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getRegions/Fault/UpbsException")
    })
    public List<Region> getRegions()
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param billerId
     * @return
     *     returns test1.Biller
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "biller", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getBillerById", targetNamespace = "http://upbs.cs.com/", className = "test1.GetBillerById")
    @ResponseWrapper(localName = "getBillerByIdResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetBillerByIdResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillerByIdRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillerByIdResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillerById/Fault/UpbsException")
    })
    public Biller getBillerById(
        @WebParam(name = "billerId", targetNamespace = "http://upbs.cs.com/")
        long billerId)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param billerId
     * @param attribute
     * @return
     *     returns test1.Bill
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "bill", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getManualBill", targetNamespace = "http://upbs.cs.com/", className = "test1.GetManualBill")
    @ResponseWrapper(localName = "getManualBillResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetManualBillResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getManualBillRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getManualBillResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getManualBill/Fault/UpbsException")
    })
    public Bill getManualBill(
        @WebParam(name = "billerId", targetNamespace = "http://upbs.cs.com/")
        long billerId,
        @WebParam(name = "attribute", targetNamespace = "http://upbs.cs.com/")
        List<SimpleAttribute> attribute)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param bills
     * @return
     *     returns java.util.List<test1.Bill>
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "bill", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "createBills", targetNamespace = "http://upbs.cs.com/", className = "test1.CreateBills")
    @ResponseWrapper(localName = "createBillsResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.CreateBillsResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/createBillsRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/createBillsResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/createBills/Fault/UpbsException")
    })
    public List<Bill> createBills(
        @WebParam(name = "bills", targetNamespace = "http://upbs.cs.com/")
        List<Bill> bills)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param signature
     * @param paymentId
     * @param certificateId
     * @return
     *     returns test1.BillSnapShot
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "billSnapShot", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "payBill", targetNamespace = "http://upbs.cs.com/", className = "test1.PayBill")
    @ResponseWrapper(localName = "payBillResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.PayBillResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/payBillRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/payBillResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/payBill/Fault/UpbsException")
    })
    public BillSnapShot payBill(
        @WebParam(name = "paymentId", targetNamespace = "http://upbs.cs.com/")
        long paymentId,
        @WebParam(name = "signature", targetNamespace = "http://upbs.cs.com/")
        String signature,
        @WebParam(name = "certificateId", targetNamespace = "http://upbs.cs.com/")
        Long certificateId)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param date
     * @param billerId
     * @param amount
     * @param currency
     * @param paymentInputChannel
     * @return
     *     returns test1.EntryListResponseWrapper
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "fee", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "calculateFee", targetNamespace = "http://upbs.cs.com/", className = "test1.CalculateFee")
    @ResponseWrapper(localName = "calculateFeeResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.CalculateFeeResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/calculateFeeRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/calculateFeeResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/calculateFee/Fault/UpbsException")
    })
    public EntryListResponseWrapper calculateFee(
        @WebParam(name = "billerId", targetNamespace = "http://upbs.cs.com/")
        long billerId,
        @WebParam(name = "amount", targetNamespace = "http://upbs.cs.com/")
        long amount,
        @WebParam(name = "date", targetNamespace = "http://upbs.cs.com/")
        XMLGregorianCalendar date,
        @WebParam(name = "currency", targetNamespace = "http://upbs.cs.com/")
        int currency,
        @WebParam(name = "paymentInputChannel", targetNamespace = "http://upbs.cs.com/")
        PaymentInputChannel paymentInputChannel)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param regionId
     * @param activeBillersOnly
     * @param needBillerSnapShots
     * @param visibleBillersOnly
     * @param mobileBillersOnly
     * @return
     *     returns java.util.List<test1.BillerSnapShotGroup>
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "billerGroup", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getBillerSnapShotGroupsByRegion", targetNamespace = "http://upbs.cs.com/", className = "test1.GetBillerSnapShotGroupsByRegion")
    @ResponseWrapper(localName = "getBillerSnapShotGroupsByRegionResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetBillerSnapShotGroupsByRegionResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillerSnapShotGroupsByRegionRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillerSnapShotGroupsByRegionResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillerSnapShotGroupsByRegion/Fault/UpbsException")
    })
    public List<BillerSnapShotGroup> getBillerSnapShotGroupsByRegion(
        @WebParam(name = "regionId", targetNamespace = "http://upbs.cs.com/")
        long regionId,
        @WebParam(name = "needBillerSnapShots", targetNamespace = "http://upbs.cs.com/")
        Boolean needBillerSnapShots,
        @WebParam(name = "activeBillersOnly", targetNamespace = "http://upbs.cs.com/")
        Boolean activeBillersOnly,
        @WebParam(name = "visibleBillersOnly", targetNamespace = "http://upbs.cs.com/")
        Boolean visibleBillersOnly,
        @WebParam(name = "mobileBillersOnly", targetNamespace = "http://upbs.cs.com/")
        Boolean mobileBillersOnly)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param activeBillersOnly
     * @param visibleBillersOnly
     * @param mobileBillersOnly
     * @param version
     * @return
     *     returns test1.ListResponseBillerShapShotsByVersionWrapper
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "billerShapShots", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getBillerSnapShotsByVersion", targetNamespace = "http://upbs.cs.com/", className = "test1.GetBillerSnapShotsByVersion")
    @ResponseWrapper(localName = "getBillerSnapShotsByVersionResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetBillerSnapShotsByVersionResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillerSnapShotsByVersionRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillerSnapShotsByVersionResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillerSnapShotsByVersion/Fault/UpbsException")
    })
    public ListResponseBillerShapShotsByVersionWrapper getBillerSnapShotsByVersion(
        @WebParam(name = "version", targetNamespace = "http://upbs.cs.com/")
        long version,
        @WebParam(name = "activeBillersOnly", targetNamespace = "http://upbs.cs.com/")
        Boolean activeBillersOnly,
        @WebParam(name = "visibleBillersOnly", targetNamespace = "http://upbs.cs.com/")
        Boolean visibleBillersOnly,
        @WebParam(name = "mobileBillersOnly", targetNamespace = "http://upbs.cs.com/")
        Boolean mobileBillersOnly)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param regionId
     * @param onlyActive
     * @param billerGroupId
     * @return
     *     returns java.util.List<test1.Biller>
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "billers", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getBillersByGroupId", targetNamespace = "http://upbs.cs.com/", className = "test1.GetBillersByGroupId")
    @ResponseWrapper(localName = "getBillersByGroupIdResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetBillersByGroupIdResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillersByGroupIdRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillersByGroupIdResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillersByGroupId/Fault/UpbsException")
    })
    public List<Biller> getBillersByGroupId(
        @WebParam(name = "billerGroupId", targetNamespace = "http://upbs.cs.com/")
        long billerGroupId,
        @WebParam(name = "regionId", targetNamespace = "http://upbs.cs.com/")
        Long regionId,
        @WebParam(name = "onlyActive", targetNamespace = "http://upbs.cs.com/")
        Boolean onlyActive)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param regionId
     * @param activeBillersOnly
     * @param visibleBillersOnly
     * @param mobileBillersOnly
     * @param needBillers
     * @return
     *     returns java.util.List<test1.BillerGroup>
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "billerGroup", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getBillerGroupsByRegion", targetNamespace = "http://upbs.cs.com/", className = "test1.GetBillerGroupsByRegion")
    @ResponseWrapper(localName = "getBillerGroupsByRegionResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetBillerGroupsByRegionResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillerGroupsByRegionRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillerGroupsByRegionResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillerGroupsByRegion/Fault/UpbsException")
    })
    public List<BillerGroup> getBillerGroupsByRegion(
        @WebParam(name = "regionId", targetNamespace = "http://upbs.cs.com/")
        long regionId,
        @WebParam(name = "needBillers", targetNamespace = "http://upbs.cs.com/")
        Boolean needBillers,
        @WebParam(name = "activeBillersOnly", targetNamespace = "http://upbs.cs.com/")
        Boolean activeBillersOnly,
        @WebParam(name = "visibleBillersOnly", targetNamespace = "http://upbs.cs.com/")
        Boolean visibleBillersOnly,
        @WebParam(name = "mobileBillersOnly", targetNamespace = "http://upbs.cs.com/")
        Boolean mobileBillersOnly)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param billerId
     * @param stepNo
     * @param previousStepAttribute
     * @return
     *     returns test1.BillConstuctorStepsWrapper
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "billStep", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "processBillConstuctorStep", targetNamespace = "http://upbs.cs.com/", className = "test1.ProcessBillConstuctorStep")
    @ResponseWrapper(localName = "processBillConstuctorStepResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.ProcessBillConstuctorStepResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/processBillConstuctorStepRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/processBillConstuctorStepResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/processBillConstuctorStep/Fault/UpbsException")
    })
    public BillConstuctorStepsWrapper processBillConstuctorStep(
        @WebParam(name = "billerId", targetNamespace = "http://upbs.cs.com/")
        long billerId,
        @WebParam(name = "stepNo", targetNamespace = "http://upbs.cs.com/")
        long stepNo,
        @WebParam(name = "previousStepAttribute", targetNamespace = "http://upbs.cs.com/")
        List<BillAttribute> previousStepAttribute)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param billerId
     * @param subscriptionName
     * @param attribute
     * @param createSubscriptionOnSuccess
     * @return
     *     returns java.util.List<test1.Bill>
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "bill", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getProviderBills", targetNamespace = "http://upbs.cs.com/", className = "test1.GetProviderBills")
    @ResponseWrapper(localName = "getProviderBillsResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetProviderBillsResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getProviderBillsRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getProviderBillsResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getProviderBills/Fault/UpbsException")
    })
    public List<Bill> getProviderBills(
        @WebParam(name = "billerId", targetNamespace = "http://upbs.cs.com/")
        long billerId,
        @WebParam(name = "attribute", targetNamespace = "http://upbs.cs.com/")
        List<SimpleAttribute> attribute,
        @WebParam(name = "createSubscriptionOnSuccess", targetNamespace = "http://upbs.cs.com/")
        Boolean createSubscriptionOnSuccess,
        @WebParam(name = "subscriptionName", targetNamespace = "http://upbs.cs.com/")
        String subscriptionName)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param batchId
     * @return
     *     returns java.util.List<test1.Bill>
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "bill", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getBillsByBatchId", targetNamespace = "http://upbs.cs.com/", className = "test1.GetBillsByBatchId")
    @ResponseWrapper(localName = "getBillsByBatchIdResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetBillsByBatchIdResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillsByBatchIdRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillsByBatchIdResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillsByBatchId/Fault/UpbsException")
    })
    public List<Bill> getBillsByBatchId(
        @WebParam(name = "batchId", targetNamespace = "http://upbs.cs.com/")
        long batchId)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param version
     * @return
     *     returns java.util.List<test1.BillSnapShot>
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "billSnapShot", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getUpbsBillSnapShotsByVersion", targetNamespace = "http://upbs.cs.com/", className = "test1.GetUpbsBillSnapShotsByVersion")
    @ResponseWrapper(localName = "getUpbsBillSnapShotsByVersionResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetUpbsBillSnapShotsByVersionResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getUpbsBillSnapShotsByVersionRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getUpbsBillSnapShotsByVersionResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getUpbsBillSnapShotsByVersion/Fault/UpbsException")
    })
    public List<BillSnapShot> getUpbsBillSnapShotsByVersion(
        @WebParam(name = "version", targetNamespace = "http://upbs.cs.com/")
        long version)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param paymentId
     * @return
     *     returns test1.Bill
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "bill", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getUpbsBillById", targetNamespace = "http://upbs.cs.com/", className = "test1.GetUpbsBillById")
    @ResponseWrapper(localName = "getUpbsBillByIdResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetUpbsBillByIdResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getUpbsBillByIdRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getUpbsBillByIdResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getUpbsBillById/Fault/UpbsException")
    })
    public Bill getUpbsBillById(
        @WebParam(name = "paymentId", targetNamespace = "http://upbs.cs.com/")
        long paymentId)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param billerId
     * @param subscriptionName
     * @param attribute
     * @param needBills
     * @return
     *     returns test1.BillSubscription
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "billSubscription", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "createBillSubscription", targetNamespace = "http://upbs.cs.com/", className = "test1.CreateBillSubscription")
    @ResponseWrapper(localName = "createBillSubscriptionResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.CreateBillSubscriptionResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/createBillSubscriptionRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/createBillSubscriptionResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/createBillSubscription/Fault/UpbsException")
    })
    public BillSubscription createBillSubscription(
        @WebParam(name = "billerId", targetNamespace = "http://upbs.cs.com/")
        long billerId,
        @WebParam(name = "attribute", targetNamespace = "http://upbs.cs.com/")
        List<SimpleAttribute> attribute,
        @WebParam(name = "subscriptionName", targetNamespace = "http://upbs.cs.com/")
        String subscriptionName,
        @WebParam(name = "needBills", targetNamespace = "http://upbs.cs.com/")
        Boolean needBills)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param billSubscriptionId
     * @throws UpbsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeBillSubscription", targetNamespace = "http://upbs.cs.com/", className = "test1.RemoveBillSubscription")
    @ResponseWrapper(localName = "removeBillSubscriptionResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.RemoveBillSubscriptionResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/removeBillSubscriptionRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/removeBillSubscriptionResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/removeBillSubscription/Fault/UpbsException")
    })
    public void removeBillSubscription(
        @WebParam(name = "billSubscriptionId", targetNamespace = "http://upbs.cs.com/")
        long billSubscriptionId)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param from
     * @param page
     * @param needBills
     * @return
     *     returns test1.BillSubscriptionListResponseWrapper
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "billSubscriptions", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getBillSubscriptionsByDate", targetNamespace = "http://upbs.cs.com/", className = "test1.GetBillSubscriptionsByDate")
    @ResponseWrapper(localName = "getBillSubscriptionsByDateResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetBillSubscriptionsByDateResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillSubscriptionsByDateRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillSubscriptionsByDateResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getBillSubscriptionsByDate/Fault/UpbsException")
    })
    public BillSubscriptionListResponseWrapper getBillSubscriptionsByDate(
        @WebParam(name = "from", targetNamespace = "http://upbs.cs.com/")
        XMLGregorianCalendar from,
        @WebParam(name = "page", targetNamespace = "http://upbs.cs.com/")
        Integer page,
        @WebParam(name = "needBills", targetNamespace = "http://upbs.cs.com/")
        Boolean needBills)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param page
     * @param version
     * @return
     *     returns test1.DictionaryListWrapper
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "vocabularyWithErrors", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getDictionaryByVersion", targetNamespace = "http://upbs.cs.com/", className = "test1.GetDictionaryByVersion")
    @ResponseWrapper(localName = "getDictionaryByVersionResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetDictionaryByVersionResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getDictionaryByVersionRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getDictionaryByVersionResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getDictionaryByVersion/Fault/UpbsException")
    })
    public DictionaryListWrapper getDictionaryByVersion(
        @WebParam(name = "version", targetNamespace = "http://upbs.cs.com/")
        Long version,
        @WebParam(name = "page", targetNamespace = "http://upbs.cs.com/")
        Integer page)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param billerId
     * @param dictionaryParams
     * @param dictionaryType
     * @param dictionaryId
     * @param page
     * @param version
     * @param rowsPerPage
     * @return
     *     returns test1.WsDictionaryResponse
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "dictRes", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getSimpleDictionary", targetNamespace = "http://upbs.cs.com/", className = "test1.GetSimpleDictionary")
    @ResponseWrapper(localName = "getSimpleDictionaryResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetSimpleDictionaryResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getSimpleDictionaryRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getSimpleDictionaryResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getSimpleDictionary/Fault/UpbsException")
    })
    public WsDictionaryResponse getSimpleDictionary(
        @WebParam(name = "billerId", targetNamespace = "http://upbs.cs.com/")
        long billerId,
        @WebParam(name = "dictionaryType", targetNamespace = "http://upbs.cs.com/")
        WsDictionaryTypeEnum dictionaryType,
        @WebParam(name = "dictionaryId", targetNamespace = "http://upbs.cs.com/")
        String dictionaryId,
        @WebParam(name = "dictionaryParams", targetNamespace = "http://upbs.cs.com/")
        WsDictionaryParams dictionaryParams,
        @WebParam(name = "version", targetNamespace = "http://upbs.cs.com/")
        Integer version,
        @WebParam(name = "page", targetNamespace = "http://upbs.cs.com/")
        Integer page,
        @WebParam(name = "rowsPerPage", targetNamespace = "http://upbs.cs.com/")
        Integer rowsPerPage)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param translationRequest
     * @return
     *     returns java.util.List<test1.Vocabulary>
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "vocabulary", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getTranslations", targetNamespace = "http://upbs.cs.com/", className = "test1.GetTranslations")
    @ResponseWrapper(localName = "getTranslationsResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetTranslationsResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getTranslationsRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getTranslationsResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getTranslations/Fault/UpbsException")
    })
    public List<Vocabulary> getTranslations(
        @WebParam(name = "translationRequest", targetNamespace = "http://upbs.cs.com/")
        List<TranslationRequest> translationRequest)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "serverVersion", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getServerVersion", targetNamespace = "http://upbs.cs.com/", className = "test1.GetServerVersion")
    @ResponseWrapper(localName = "getServerVersionResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetServerVersionResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getServerVersionRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getServerVersionResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getServerVersion/Fault/UpbsException")
    })
    public String getServerVersion()
        throws UpbsException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<test1.CityGerc>
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "gercCityDictionary", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getGercCityDictionary", targetNamespace = "http://upbs.cs.com/", className = "test1.GetGercCityDictionary")
    @ResponseWrapper(localName = "getGercCityDictionaryResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetGercCityDictionaryResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercCityDictionaryRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercCityDictionaryResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercCityDictionary/Fault/UpbsException")
    })
    public List<CityGerc> getGercCityDictionary()
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param cityId
     * @return
     *     returns java.util.List<test1.StreetGerc>
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "gercStreetDictionary", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getGercStreetDictionary", targetNamespace = "http://upbs.cs.com/", className = "test1.GetGercStreetDictionary")
    @ResponseWrapper(localName = "getGercStreetDictionaryResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetGercStreetDictionaryResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercStreetDictionaryRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercStreetDictionaryResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercStreetDictionary/Fault/UpbsException")
    })
    public List<StreetGerc> getGercStreetDictionary(
        @WebParam(name = "cityId", targetNamespace = "http://upbs.cs.com/")
        long cityId)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param streetId
     * @return
     *     returns java.util.List<test1.HouseGerc>
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "gercHouseDictionary", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getGercHouseDictionary", targetNamespace = "http://upbs.cs.com/", className = "test1.GetGercHouseDictionary")
    @ResponseWrapper(localName = "getGercHouseDictionaryResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetGercHouseDictionaryResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercHouseDictionaryRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercHouseDictionaryResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercHouseDictionary/Fault/UpbsException")
    })
    public List<HouseGerc> getGercHouseDictionary(
        @WebParam(name = "streetId", targetNamespace = "http://upbs.cs.com/")
        long streetId)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param houseId
     * @return
     *     returns java.util.List<test1.FlatGerc>
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "gercFlatDictionary", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getGercFlatDictionary", targetNamespace = "http://upbs.cs.com/", className = "test1.GetGercFlatDictionary")
    @ResponseWrapper(localName = "getGercFlatDictionaryResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetGercFlatDictionaryResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercFlatDictionaryRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercFlatDictionaryResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercFlatDictionary/Fault/UpbsException")
    })
    public List<FlatGerc> getGercFlatDictionary(
        @WebParam(name = "houseId", targetNamespace = "http://upbs.cs.com/")
        long houseId)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param flatId
     * @return
     *     returns java.util.List<test1.OwnerGerc>
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "gercOwnerDictionary", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getGercOwnerDictionary", targetNamespace = "http://upbs.cs.com/", className = "test1.GetGercOwnerDictionary")
    @ResponseWrapper(localName = "getGercOwnerDictionaryResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetGercOwnerDictionaryResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercOwnerDictionaryRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercOwnerDictionaryResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercOwnerDictionary/Fault/UpbsException")
    })
    public List<OwnerGerc> getGercOwnerDictionary(
        @WebParam(name = "flatId", targetNamespace = "http://upbs.cs.com/")
        long flatId)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param account
     * @return
     *     returns java.util.List<test1.PlatCodeInfo>
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "gercPlatCodeInfo", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getGercPlatCodeInfo", targetNamespace = "http://upbs.cs.com/", className = "test1.GetGercPlatCodeInfo")
    @ResponseWrapper(localName = "getGercPlatCodeInfoResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetGercPlatCodeInfoResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercPlatCodeInfoRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercPlatCodeInfoResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercPlatCodeInfo/Fault/UpbsException")
    })
    public List<PlatCodeInfo> getGercPlatCodeInfo(
        @WebParam(name = "account", targetNamespace = "http://upbs.cs.com/")
        String account)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param action
     * @param smena
     * @return
     *     returns test1.KassActionResponse
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "gercKassAction", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "gercKassAction", targetNamespace = "http://upbs.cs.com/", className = "test1.GercKassAction")
    @ResponseWrapper(localName = "gercKassActionResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GercKassActionResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/gercKassActionRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/gercKassActionResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/gercKassAction/Fault/UpbsException")
    })
    public KassActionResponse gercKassAction(
        @WebParam(name = "action", targetNamespace = "http://upbs.cs.com/")
        int action,
        @WebParam(name = "smena", targetNamespace = "http://upbs.cs.com/")
        Integer smena)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @param bills
     * @return
     *     returns java.util.List<test1.Bill>
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "bill", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "calculateTariffs", targetNamespace = "http://upbs.cs.com/", className = "test1.CalculateTariffs")
    @ResponseWrapper(localName = "calculateTariffsResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.CalculateTariffsResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/calculateTariffsRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/calculateTariffsResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/calculateTariffs/Fault/UpbsException")
    })
    public List<Bill> calculateTariffs(
        @WebParam(name = "bills", targetNamespace = "http://upbs.cs.com/")
        List<Bill> bills)
        throws UpbsException_Exception
    ;


    /**
     * 
     * @param id
     * @param type
     * @return
     *     returns java.util.List<test1.GercDictionaryEntity>
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "gercDictionaryEntity", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "getGercDictionaryByType", targetNamespace = "http://upbs.cs.com/", className = "test1.GetGercDictionaryByType")
    @ResponseWrapper(localName = "getGercDictionaryByTypeResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.GetGercDictionaryByTypeResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercDictionaryByTypeRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercDictionaryByTypeResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/getGercDictionaryByType/Fault/UpbsException")
    })
    public List<GercDictionaryEntity> getGercDictionaryByType(
        @WebParam(name = "id", targetNamespace = "http://upbs.cs.com/")
        Long id,
        @WebParam(name = "type", targetNamespace = "http://upbs.cs.com/")
        DictionaryType type)
        throws UpbsException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.Boolean
     * @throws UpbsException_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://upbs.cs.com/")
    @RequestWrapper(localName = "clearCaches", targetNamespace = "http://upbs.cs.com/", className = "test1.ClearCaches")
    @ResponseWrapper(localName = "clearCachesResponse", targetNamespace = "http://upbs.cs.com/", className = "test1.ClearCachesResponse")
    @Action(input = "http://upbs.cs.com/PaymentBrokerEndpoint/clearCachesRequest", output = "http://upbs.cs.com/PaymentBrokerEndpoint/clearCachesResponse", fault = {
        @FaultAction(className = UpbsException_Exception.class, value = "http://upbs.cs.com/PaymentBrokerEndpoint/clearCaches/Fault/UpbsException")
    })
    public Boolean clearCaches()
        throws UpbsException_Exception
    ;

}
