
package test1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PaymentBrokerEndpointService", targetNamespace = "http://upbs.cs.com/", wsdlLocation = "http://localhost:9580/UPBS/paymentBroker/PaymentBroker-Service?wsdl")
public class PaymentBrokerEndpointService
    extends Service
{

    private final static URL PAYMENTBROKERENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAYMENTBROKERENDPOINTSERVICE_EXCEPTION;
    private final static QName PAYMENTBROKERENDPOINTSERVICE_QNAME = new QName("http://upbs.cs.com/", "PaymentBrokerEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9580/UPBS/paymentBroker/PaymentBroker-Service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYMENTBROKERENDPOINTSERVICE_WSDL_LOCATION = url;
        PAYMENTBROKERENDPOINTSERVICE_EXCEPTION = e;
    }

    public PaymentBrokerEndpointService() {
        super(__getWsdlLocation(), PAYMENTBROKERENDPOINTSERVICE_QNAME);
    }

    public PaymentBrokerEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENTBROKERENDPOINTSERVICE_QNAME, features);
    }

    public PaymentBrokerEndpointService(URL wsdlLocation) {
        super(wsdlLocation, PAYMENTBROKERENDPOINTSERVICE_QNAME);
    }

    public PaymentBrokerEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENTBROKERENDPOINTSERVICE_QNAME, features);
    }

    public PaymentBrokerEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentBrokerEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentBrokerEndpoint
     */
    @WebEndpoint(name = "PaymentBrokerEndpointPort")
    public PaymentBrokerEndpoint getPaymentBrokerEndpointPort() {
        return super.getPort(new QName("http://upbs.cs.com/", "PaymentBrokerEndpointPort"), PaymentBrokerEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentBrokerEndpoint
     */
    @WebEndpoint(name = "PaymentBrokerEndpointPort")
    public PaymentBrokerEndpoint getPaymentBrokerEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://upbs.cs.com/", "PaymentBrokerEndpointPort"), PaymentBrokerEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENTBROKERENDPOINTSERVICE_EXCEPTION!= null) {
            throw PAYMENTBROKERENDPOINTSERVICE_EXCEPTION;
        }
        return PAYMENTBROKERENDPOINTSERVICE_WSDL_LOCATION;
    }

}
