
package test1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UpbsException", targetNamespace = "http://upbs.cs.com/")
public class UpbsException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UpbsException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UpbsException_Exception(String message, UpbsException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public UpbsException_Exception(String message, UpbsException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: test1.UpbsException
     */
    public UpbsException getFaultInfo() {
        return faultInfo;
    }

}
